// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"github.com/aqaurius6666/faas-pkg/database"
)

// Injectors from wire.go:

func NewModel(o Option) (Model, error) {
	repository := o.Repository
	modelImpl := &ModelImpl{
		Repository: repository,
	}
	return modelImpl, nil
}

// wire.go:

type Option struct {
	Repository database.Repository
}
